funds:
  - fund_name: Applebead
    date_regex: "\\d{2}-\\d{2}-\\d{4}"
    date_format: "%d-%m-%Y"
  - fund_name: Belaware
    date_regex: "\\d{2}_\\d{2}_\\d{4}"
    date_format: "%d_%m_%Y"
  - fund_name: Whitestone
    date_regex: "\\d{2}-\\d{2}-\\d{4}"
    date_format: "%d-%m-%Y"
  - fund_name: Leeder
    date_regex: "\\d{2}_\\d{2}_\\d{4}"
    date_format: "%m_%d_%Y"
  - fund_name: Magnum
    date_regex: "\\d{2}-\\d{2}-\\d{4}"
    date_format: "%d-%m-%Y"
  - fund_name: Wallington
    date_regex: "\\d{2}_\\d{2}_\\d{4}"
    date_format: "%d_%m_%Y"
  - fund_name: Gohen
    date_regex: "\\d{2}-\\d{2}-\\d{4}"
    date_format: "%m-%d-%Y"
  - fund_name: Catalysm
    date_regex: "\\d{4}-\\d{2}-\\d{2}"
    date_format: "%Y-%m-%d"
  - fund_name: Trustmind
    date_regex: "\\d{8}"
    date_format: "%Y%m%d"
  - fund_name: Virtous
    date_regex: "\\d{2}-\\d{2}-\\d{4}"
    date_format: "%m-%d-%Y"